### ISSUE TITLE
How to share session in the child application?

### ISSUE THREAD

**Issue by HackerLZH** [webpy/webpy.github.com#141]
The version of official cookbook is still 0.3 but I use the latest 0.61.When I learn how to share session in the child application, the solution given by official cookbook can't work. For example, after I used "session = web.ctx.session" in the child application, it reported an error as "AttributeError: 'ThreadedDict' object has no attribute 'session'" .It just did't share the session at all.
What should I do?

**Comment by cclauss** [comment]
Parent: `web.ctx.session = session`
Child: `session = dict(web.ctx).get('session')`

**Comment by HackerLZH** [comment]
Oh, I have written "session = web.session.Session(app, store, initializer={'login': 0, 'username': ''})" in my parent application. After I modified like you and used 'session.login' in the child application, it reported an error as "AttributeError: 'NoneType' object has no attribute 'login'". So it just means the session I get is None.

**Comment by cclauss** [comment]
Let's use assertions to see where the problem lies...

Parent:
```python
web.cxt.session = web.session.Session(app, store, initializer={'login': 0, 'username': ''})
assert web.cxt.session, "Login failed!"
```
Child:
```python
session = dict(web.ctx).get('session')
assert session, "Invalid session provided."
```

**Comment by HackerLZH** [comment]
> Let's use assertions to see where the problem lies...
> Parent:
> web.cxt.session = web.session.Session(app, store, initializer={'login': 0, 'username': ''})
> assert web.cxt.session, "Login failed!"
> Child:
> session = dict(web.ctx).get('session')
> assert session, "Invalid session provided."

Traceback (most recent call last):
  File "D:/Python/web.py/main.py", line 3, in <module>
    import enter
  File "D:\Python\web.py\enter.py", line 23, in <module>
    assert session, "Invalid session provided."
AssertionError: Invalid session provided.

Ok, Invaid session provided

**Comment by cclauss** [comment]
Are we sure that the parent lines have already been run?

**Comment by HackerLZH** [comment]
> Are we sure that the parent lines have already been run?

//parent.py
`
import web
import child
web.config.debug = False

urls = (
    '/child', child.app_child,
)

app = web.application(urls, globals())
db = web.database(
    dbn='mysql',
    host='127.0.0.1',
    port=3306,
    user='root',
    pw='lzh420821',
    db='webpy',
)

store = web.session.DBStore(db, 'sessions')
session = web.session.Session(app, store, initializer={'login': 0, 'username': ''})
web.ctx.session = session


if __name__ == '__main__':
    app.run()
`

//child.py
`
import web
web.config.debug = False

urls = (
    '/hello', 'hello'
)

app_child = web.application(urls, globals())

session = dict(web.ctx).get('session')

class hello():
    def GET(self):
        return session.login
`
Something like that!

**Comment by cclauss** [comment]
Nope.  (The previous post was reformatted with  \`\`\`python and \`\`\` for readability.)

The problem is that the line `import child` is going to run ___all code at global scope___ in `client.py`.  This will mean that the client.py line `session = dict(web.ctx).get('session')` will get run ___before___ the parent.py line `web.ctx.session = session`

**Comment by HackerLZH** [comment]
> Nope.  (The previous post was reformatted with  ```python and ``` for readability.)
> The problem is that the line import child is going to run all code at global scope in client.py.  This will mean that the client.py line session = dict(web.ctx).get('session') will get run before the parent.py line web.ctx.session = session

So that's it, how can I run after the parent.py?

**Comment by cclauss** [comment]
Many ways to do it but perhaps the simplest is...
```python
import web
web.config.debug = False

urls = (
    '/hello', 'hello'
)

app_child = web.application(urls, globals())

class hello():
    def GET(self):
        return dict(web.ctx).get('session').login
```

**Comment by HackerLZH** [comment]
> Many ways to do it but perhaps the simplest is...
> import web
> web.config.debug = False
> 
> urls = (
>     '/hello', 'hello'
> )
> 
> app_child = web.application(urls, globals())
> 
> class hello():
>     def GET(self):
>         return web.ctx.session.login

AttributeError: 'ThreadedDict' object has no attribute 'session'

No way, I think I just return to initial time! The simplest way you gave is the same as official cookbook.But it's version 0.3,and  I use version 0.61.And I have tried the official cookbook twelve hours ago. I need the latest usage!

**Comment by HackerLZH** [comment]
I use python38， not python2
